# -*- coding: utf-8 -*-
"""RED 2 BERT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwaLsK7orVszdMeItwKt04Q01QAKT106
"""

# CELDA 1
!pip -q install sentence-transformers torch torchvision torchaudio scikit-learn pandas numpy tqdm

# CELDA 2

import os, json, math, random
import numpy as np
import pandas as pd
from tqdm import tqdm

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# CELDA 3

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

# Clases base + innovadoras (puedes comentar las que no quieras)
LABELS = [
    "VIDEO",
    "LECTURA_PDF",
    "PRESENTACION",
    "SIMULACION_INTERACTIVA",
    "ACTIVIDAD_PRACTICA",
    "EVALUACION_CUESTIONARIO",
    # innovadoras:
    "DEBATE_SOCRATICO",
    "PROYECTO_MAKER",
    "MAPA_CONCEPTUAL",
    "JUEGO_GAMIFICADO",
]

label2id = {l:i for i,l in enumerate(LABELS)}
id2label = {i:l for l,i in label2id.items()}

# Áreas (orden fijo)
AREA_ORDER = [
    "MATEMATICA",
    "COMUNICACION_Y_LENGUAJES",
    "CIENCIAS_NATURALES_BIOLOGIA",
    "FISICA",
    "QUIMICA",
    "CIENCIAS_SOCIALES",
    "VALORES_ESPIRITUALIDAD_RELIGIONES",
    "TECNOLOGIA_PRODUCTIVA"
]
area2idx = {a:i for i,a in enumerate(AREA_ORDER)}

# Dimensiones (orden fijo)
DIM_ORDER = ["SER", "HACER", "SABER", "DECIDIR"]

# Embeddings
SBERT_NAME = "sentence-transformers/all-MiniLM-L6-v2"  # 384 dims (rápido y bueno)
EMB_DIM = 384

# Entrenamiento
BATCH_SIZE = 32
EPOCHS = 6
LR = 2e-4
DROPOUT = 0.2


# -------------------------
# ✅ NUEVO: Pesos para darle MÁS influencia a Red1 (A y D)
# -------------------------
W_AREA = 4.0   # prueba: 3 a 6 suele ser buen rango
W_DIMS = 4.0   # idem
# Si quieres que Red1 mande más: sube a 6 u 8

# -------------------------
# ✅ NUEVO: Umbrales para decidir si consulta es ESPECÍFICA o GENERAL (por similitudes)
# -------------------------
CHUNK_TOPK_SPEC = 3     # usar top-3 chunks para preguntas específicas
CHUNK_TOPK_GEN  = 12    # usar top-12 chunks para preguntas generales (o todos si hay menos)
SIM_TOP1_SPEC_TH = 0.50 # si top1 >= esto...
SIM_GAP_SPEC_TH  = 0.08 # ...y top1-top3 >= esto -> ESPECÍFICA
TEMP_SPEC = 0.07        # temperatura softmax baja -> se concentra en top chunks
TEMP_GEN  = 0.18        # temperatura más alta -> promedia más

# CELDA 4
# Cargar datos (desde JSON exportado de Supabase)

# Pon aquí tu ruta al archivo exportado (subido a Colab)
DATA_PATH = "/content/datos_mix_enriched.json"  # cambia si es .json

def load_rows(path):
    rows = []
    if path.endswith(".jsonl"):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                rows.append(json.loads(line))
    else:
        with open(path, "r", encoding="utf-8") as f:
            rows = json.load(f)
    return rows

raw = load_rows(DATA_PATH)
print("filas cargadas:", len(raw))
print("keys ejemplo:", raw[0].keys())

# CELDA 5
# A veces un campo viene null, o con estructura distinta. Aquí lo dejamos “limpio”.

def safe_get_dims_probs(row):
    # puede venir en row["dims_probs"] o en row["salida"]["dims_probs"]
    if isinstance(row.get("dims_probs"), dict):
        return row["dims_probs"]
    salida = row.get("salida", {})
    if isinstance(salida, dict) and isinstance(salida.get("dims_probs"), dict):
        return salida["dims_probs"]
    return None

def safe_get_areas_top(row):
    salida = row.get("salida", {})
    if isinstance(salida, dict) and isinstance(salida.get("areas_top"), list):
        return salida["areas_top"]
    return row.get("areas_top", None)

def normalize_row(row):
    row_id = row.get("id")  # ✅ conservar id de Supabase

    #text = row.get("texto_resumen") or ""
    text = row.get("texto_resumen") or row.get("contenido") or ""

    text = str(text).strip()

    tipo = row.get("tipo_fuente") or "archivo"
    tipo = tipo.lower().strip()

    dims_probs = safe_get_dims_probs(row)
    areas_top = safe_get_areas_top(row)

    return {
        "id": row_id,            # ✅ NUEVO
        "text": text,
        "tipo_fuente": tipo,
        "dims_probs": dims_probs,
        "areas_top": areas_top,
    }

data = [normalize_row(r) for r in raw]
# filtra basura vacía
data = [d for d in data if len(d["text"]) >= 10]
print("filas útiles:", len(data))
print(data[0])


import re

META_PATTERNS = [
    r"\bpor\s+que\s+me\s+respondiste\b",
    r"\ben\s+tus\s+archivos\b",
    r"\bsolo\s+puse\b",
    r"\bno\s+quiero\s+que\s+respondas\b",
    r"\btu\s+sistema\b",
    r"\bestas\s+mal\b",
    r"\bno\s+entiendes\b",
    r"\bme\s+diste\b.*\brespuesta\b",
    r"\berror\b",
    r"\bbroken\b",
    r"\bbug\b",
]

def is_meta_system(text: str) -> bool:
    t = (text or "").strip().lower()
    if len(t) < 5:
        return True
    return any(re.search(p, t) for p in META_PATTERNS)

# aplica filtro
data = [d for d in data if len(d["text"]) >= 10 and not is_meta_system(d["text"])]
print("filas útiles (sin meta-sistema):", len(data))

# CELDA 6
# Construir features numéricas desde Red 1 (A, D, T, meta), convertimos la salida de Red 1 en números fijos.

def build_area_vec(areas_top):
    A = np.zeros(len(AREA_ORDER), dtype=np.float32)
    if isinstance(areas_top, list):
        for item in areas_top:
            area = item.get("area")
            score = item.get("score", 0.0)
            if area in area2idx:
                A[area2idx[area]] = float(score)
    return A

def build_dims_vec(dims_probs):
    # si no hay dims, ponemos uniforme 0.25 (neutral)
    D = np.array([0.25, 0.25, 0.25, 0.25], dtype=np.float32)
    if isinstance(dims_probs, dict):
        D = np.array([float(dims_probs.get(k, 0.25)) for k in DIM_ORDER], dtype=np.float32)
    return D

def build_tipo_vec(tipo_fuente):
    return np.array([1.0 if tipo_fuente == "mensaje" else 0.0], dtype=np.float32)

def build_meta_vec(text):
    # longitud suavizada (0..1 aprox)
    L = min(len(text) / 800.0, 1.0)
    return np.array([L], dtype=np.float32)

# prueba rápida
ex = data[0]
print(build_area_vec(ex["areas_top"]).shape, build_dims_vec(ex["dims_probs"]), build_tipo_vec(ex["tipo_fuente"]), build_meta_vec(ex["text"]))

# CELDA 7
# Etiquetado automático inicial (weak labeling)

# CELDA 7
# Etiquetado automático inicial (weak labeling)

import re  # ✅ NUEVO

# ✅ NUEVO: patrones simples para detectar "mensaje genérico corto"
GENERIC_MSG_PATTERNS = [
    r"\bdime\s+algo\s+sobre\b",
    r"\bexplicame\b",
    r"\bexplica\b",
    r"\bque\s+es\b",
    r"\bque\s+son\b",
    r"\bhablame\s+de\b",
    r"\bresumen\b",
    r"\bdefinicion\b",
]

# ✅ NUEVO: helper
def is_generic_short_message(text: str, max_words: int = 10) -> bool:
    t = (text or "").strip().lower()
    if not t:
        return False
    wc = len(re.findall(r"\w+", t))
    if wc > max_words:
        return False
    return any(re.search(p, t) for p in GENERIC_MSG_PATTERNS)

def weak_label(text, dims_probs):
    t = text.lower()
    D = build_dims_vec(dims_probs)
    p_ser, p_hacer, p_saber, p_decidir = D

    # Reglas por palabras (muy simples)


    if any(w in t for w in ["debate", "debaten", "debatir",
        "discute", "discuten", "discutir", "discusion",
        "argumenta", "argumentan", "argumentar", "argumentacion",
        "opina", "opinan", "opinar", "opinion",
        "defiende", "defienden", "defender",
        "justifica", "justifican", "justificar",
        "contrargumenta", "contrargumentan",
        "reflexiona", "reflexionan", "reflexionar",
        "analiza criticamente", "analisis critico",
        "postura", "posicion", "punto de vista",
        "dialoga", "dialogan", "dialogar",
        "mesa redonda", "foro", "discusion grupal"]):
        return "DEBATE_SOCRATICO"

    if any(w in t for w in ["mapa conceptual", "mapa mental",
        "organiza ideas", "organizan ideas",
        "organizador grafico",
        "esquema", "esquematiza", "esquematizan",
        "diagrama", "diagraman",
        "red conceptual",
        "cuadro sinoptico",
        "estructura conceptual",
        "jerarquiza", "jerarquizan",
        "relaciona conceptos", "relacionan conceptos",
        "clasifica ideas", "clasifican ideas",
        "diagrama de flujo",
        "tabla comparativa",
        "organiza la informacion"]):
        return "MAPA_CONCEPTUAL"

    if any(w in t for w in ["cuestionario", "evalua", "evaluan", "evaluar", "evaluacion",
        "prueba", "examen", "test",
        "preguntas de opcion multiple",
        "opcion multiple", "seleccion multiple",
        "verdadero o falso",
        "responde las preguntas", "responden preguntas",
        "completa el test", "completan el test",
        "items", "reactivos",
        "instrumento de evaluacion",
        "autoevaluacion", "heteroevaluacion",
        "rubrica", "califica", "califican",
        "mide conocimientos", "verifica aprendizajes"]):
        return "EVALUACION_CUESTIONARIO"

    if any(w in t for w in ["simula", "simulan", "simular", "simulacion",
        "experimento virtual", "laboratorio virtual",
        "phet", "interactivo", "interactiva",
        "manipula variables", "manipulan variables",
        "modifica parametros", "modifican parametros",
        "modelo interactivo", "modelado",
        "entorno virtual",
        "simulador", "usan simulador",
        "explora escenarios",
        "ajusta variables",
        "dinamica interactiva"]):
        return "SIMULACION_INTERACTIVA"

    if any(w in t for w in ["presentacion", "presentan", "presenta", "presentar",
        "diapositivas", "ppt", "powerpoint", "canva",
        "exponen", "expone", "exponer",
        "exposicion oral",
        "ponencia", "charla", "conferencia",
        "slides",
        "explican el tema",
        "muestran resultados",
        "defienden su trabajo"]):
        return "PRESENTACION"

    if any(w in t for w in ["video", "youtube", "documental",
        "ver un video", "observan un video",
        "recurso audiovisual", "material audiovisual",
        "contenido multimedia",
        "clip educativo",
        "proyeccion",
        "analizan un video",
        "visualizan contenido",
        "pelicula educativa"]):
        return "VIDEO"

    if any(w in t for w in ["proyecto", "trabajan en proyecto",
        "aprendizaje basado en proyectos",
        "construye", "construyen", "construir",
        "crea", "crean", "crear",
        "disena", "disenan", "disenar",
        "elabora", "elaboran",
        "fabrican", "fabricar",
        "prototipo", "desarrollan prototipo",
        "maqueta",
        "producto final",
        "feria cientifica",
        "maker",
        "innovacion",
        "emprendimiento",
        "resuelven un problema real"]):
        return "PROYECTO_MAKER"

    if any(w in t for w in ["juego", "juegan",
        "gamifica", "gamifican", "gamificacion",
        "misiones", "mision",
        "ganan puntos", "acumulan puntos",
        "insignias", "recompensas",
        "escape room",
        "reto", "retos",
        "desafio", "desafios",
        "competencia", "compiten",
        "ranking", "tabla de posiciones",
        "dinamica ludica",
        "actividad ludica",
        "aprendizaje basado en juegos"]):
        return "JUEGO_GAMIFICADO"

    # Reglas por “intención” (usando dims)
    # Si HACER alto -> actividad práctica
    if p_hacer >= 0.52:
        return "ACTIVIDAD_PRACTICA"

    # Si SABER alto -> lectura o video (depende de longitud)
    if p_saber >= 0.52:
        return "LECTURA_PDF" if len(t) > 400 else "VIDEO"

    # Si SER o DECIDIR alto -> debate/roleplay (innovación)
    if (p_ser >= 0.52 or p_decidir >= 0.52):
        return "DEBATE_SOCRATICO"

    # ✅ NUEVO: reglas extra (2 reglas) antes del fallback
    # 1) Mensaje corto y genérico -> VIDEO
    if is_generic_short_message(text) and len(t) < 120:
        return "VIDEO"

    # 2) Texto largo (típico de archivo/chunk) sin intención explícita -> LECTURA_PDF
    if len(t) > 300:
        return "LECTURA_PDF"

    # fallback razonable
    return "LECTURA_PDF"


# crea etiquetas iniciales
for d in data:
    d["y_weak"] = weak_label(d["text"], d["dims_probs"])

# verifica distribución
s = pd.Series([d["y_weak"] for d in data]).value_counts()
print(s)

# CELDA 8
# Exportar una muestra para corregir a mano, aquí sacas 300 filas para que tú las corrijas rápido en Excel/Sheets.
# Luego las vuelves a subir como labels_fixed.csv

# Escribir la respuesta correcta en la columna y_fixed en caso de que la fila no sirva colocar SÑIP para que esa linea no entre al entrenamiento
!pip -q install openpyxl

import re, random
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment
from openpyxl.worksheet.datavalidation import DataValidation

SAMPLE_N = 1900
sample = random.sample(data, min(SAMPLE_N, len(data)))

def clean_key(s: str) -> str:
    # clave estable (NO para visual, para matching)
    s = str(s)
    s = s.replace("\r\n", "\n").replace("\r", "\n")
    s = re.sub(r"\s+", " ", s).strip()
    return s

def pretty_text(s: str) -> str:
    # visual agradable (con saltos reales)
    s = str(s)
    s = s.replace("\r\n", "\n").replace("\r", "\n")
    s = re.sub(r"[ \t]+", " ", s).strip()
    return s

df_sample = pd.DataFrame([{
    "id_key": d.get("id", ""),  # ✅ ID REAL de la fila en Supabase
    "text": pretty_text(d.get("text") or ""),  # ✅ más seguro
    "tipo_fuente": d.get("tipo_fuente", ""),
    "y_weak": d.get("y_weak", ""),
    "y_fixed": ""                            # tú llenas
} for d in sample])


OUT_XLSX = "/content/muestra_para_corregir.xlsx"
df_sample.to_excel(OUT_XLSX, index=False)

# Post-procesar con openpyxl: wrap, anchos, altura filas, dropdown
wb = load_workbook(OUT_XLSX)
ws = wb.active
ws.title = "correccion"

# Ajustes de columnas
col_widths = {
    "A": 45,   # id_key
    "B": 90,   # text
    "C": 14,   # tipo_fuente
    "D": 24,   # y_weak
    "E": 24,   # y_fixed
}
for col, w in col_widths.items():
    ws.column_dimensions[col].width = w

# Wrap text para text y alinear arriba
wrap = Alignment(wrap_text=True, vertical="top")
for row in range(2, ws.max_row + 1):
    ws[f"B{row}"].alignment = wrap   # text
    ws[f"E{row}"].alignment = Alignment(vertical="top")
    ws.row_dimensions[row].height = 80  # altura cómoda (ajusta si quieres)

# Dropdown (validación) en y_fixed
labels_str = ",".join(LABELS)  # lista simple
dv = DataValidation(type="list", formula1=f'"{labels_str}"', allow_blank=True)
ws.add_data_validation(dv)
dv.add(f"E2:E{ws.max_row}")

# Congelar encabezado
ws.freeze_panes = "A2"

wb.save(OUT_XLSX)

print("✅ guardado:", OUT_XLSX)
print("FILAS:", len(df_sample))
df_sample.head(3)

print(df_sample["tipo_fuente"].value_counts())
print(df_sample["y_weak"].value_counts().head(10))

# CELDA 9

# si subes un csv con correcciones:
# CELDA 9 — leer correcciones desde XLSX
import os

FIXED_PATH = "/content/muestra_para_corregir_2_corregido_sin_dramatizacion.xlsx"  # o el nombre que subas corregido

fixed_map = {}
if os.path.exists(FIXED_PATH):
    df_fix = pd.read_excel(FIXED_PATH)   # ✅ CORRECTO PARA XLSX
    for _, r in df_fix.iterrows():
        key = str(r["id_key"]).strip()   # 👈 usamos id_key
        y = str(r["y_fixed"]).strip()
        if y in label2id:
            fixed_map[key] = y
    print("correcciones cargadas:", len(fixed_map))
else:
    print("no hay XLSX corregido, usando y_weak")

def get_final_label(d):
    key = str(d.get("id","")).strip()   # ✅ usa el id real
    if key in fixed_map:
        return fixed_map[key]
    return d["y_weak"]



items = []
for d in data:
    y = get_final_label(d)
    if y not in label2id:
        continue
    items.append({
        "text": d["text"],
        "tipo_fuente": d["tipo_fuente"],
        "areas_top": d["areas_top"],
        "dims_probs": d["dims_probs"],
        "label": y
    })

print("items listos:", len(items))
print(items[0]["label"])

# CELDA 10

# separa datos para evaluar si aprende de verdad. ENTRENA CON UN 80% Y EVALUA UN 20% DE LAS LINEAS O DATASET

from collections import Counter
cnt = Counter([it["label"] for it in items])
min_per_class = 5

items_bal = [it for it in items if cnt[it["label"]] >= min_per_class]

train_items, val_items = train_test_split(
    items_bal, test_size=0.4, random_state=SEED,
    stratify=[it["label"] for it in items_bal]
)

print("train:", len(train_items), "val:", len(val_items))

# CELDA 11

# Cargar SBERT y precalcular embeddings (cache) Explicación: generar embeddings es lo más pesado. Aquí los calculamos una vez.

sbert = SentenceTransformer(SBERT_NAME, device=DEVICE)

def embed_texts(texts, batch_size=64):
    embs = []
    for i in tqdm(range(0, len(texts), batch_size), desc="embeddings"):
        batch = texts[i:i+batch_size]
        e = sbert.encode(batch, convert_to_numpy=True, normalize_embeddings=True)
        embs.append(e.astype(np.float32))
    return np.vstack(embs)

train_texts = [it["text"] for it in train_items]
val_texts   = [it["text"] for it in val_items]

train_E = embed_texts(train_texts)
val_E   = embed_texts(val_texts)

print(train_E.shape, val_E.shape)

# CELDA 12

# Construir X = concat(E, A, D, T, meta) Explicación: aquí creamos el vector final que entra al MLP.

def build_X(items, E, w_area=W_AREA, w_dims=W_DIMS):
    X = []
    y = []
    for it, e in tqdm(list(zip(items, E)), total=len(items), desc="build_X"):
        A = build_area_vec(it["areas_top"]) * float(w_area)
        D = build_dims_vec(it["dims_probs"]) * float(w_dims)
        T = build_tipo_vec(it["tipo_fuente"])
        M = build_meta_vec(it["text"])

        x = np.concatenate([e, A, D, T, M], axis=0).astype(np.float32)
        X.append(x)
        y.append(label2id[it["label"]])

    return np.vstack(X), np.array(y, dtype=np.int64)


train_X, train_y = build_X(train_items, train_E)
val_X, val_y     = build_X(val_items, val_E)

print("X shape:", train_X.shape, "y:", train_y.shape)

# CELDA 13

# Dataset y Dataloader Explicación: permite entrenar por lotes.

class SimpleDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_ds = SimpleDataset(train_X, train_y)
val_ds   = SimpleDataset(val_X, val_y)

train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_dl   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)

print("Train dataset size:", len(train_ds))
print("Val dataset size:", len(val_ds))

xb, yb = next(iter(train_dl))
print("Batch X shape:", xb.shape)
print("Batch y shape:", yb.shape)
print("Labels únicas en batch:", torch.unique(yb))

#CELDA C

from collections import Counter
from torch.utils.data import WeightedRandomSampler

counts = Counter(train_y.tolist())
print("train class counts:", {id2label[k]: v for k,v in sorted(counts.items())})

# Pesos por ejemplo (inverso suave: 1/sqrt(freq) para que NO sea tan agresivo)
class_counts = np.array([counts.get(i, 1) for i in range(NUM_CLASSES)], dtype=np.float32)
class_weights = 1.0 / np.sqrt(class_counts)   # ✅ SUAVE
class_weights = class_weights / class_weights.mean()

sample_weights = np.array([class_weights[y] for y in train_y], dtype=np.float32)
sampler = WeightedRandomSampler(weights=sample_weights, num_samples=len(sample_weights), replacement=True)

train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler)
val_dl   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)

print("✅ train_dl balanceado (SUAVE) con sampler 1/sqrt(freq)")

# CELDA 14

# Modelo MLP Explicación: red pequeña que aprende a mapear X → probabilidades de clase.

INPUT_DIM = train_X.shape[1]
NUM_CLASSES = len(LABELS)

class MLPClassifier(nn.Module):
    def __init__(self, input_dim, num_classes, dropout=0.2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.net(x)

model = MLPClassifier(INPUT_DIM, NUM_CLASSES, dropout=DROPOUT).to(DEVICE)
print(model)

xb, _ = next(iter(train_dl))
xb = xb.to(DEVICE)
out = model(xb)

print("Output shape:", out.shape)

# ✅ CELDA 15+16 UNIFICADA: Entrenamiento + Evaluación final (reporte + confusion matrix)

optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
criterion = nn.CrossEntropyLoss(label_smoothing=0.05)

def run_epoch(dl, train=True):
    model.train(train)
    total_loss = 0.0
    all_preds, all_true = [], []

    for Xb, yb in dl:
        Xb, yb = Xb.to(DEVICE), yb.to(DEVICE)

        if train:
            optimizer.zero_grad()

        logits = model(Xb)
        loss = criterion(logits, yb)

        if train:
            loss.backward()
            optimizer.step()

        total_loss += loss.item() * len(yb)
        preds = torch.argmax(logits, dim=1)
        all_preds.append(preds.detach().cpu().numpy())
        all_true.append(yb.detach().cpu().numpy())

    all_preds = np.concatenate(all_preds) if len(all_preds) else np.array([])
    all_true  = np.concatenate(all_true)  if len(all_true)  else np.array([])

    avg_loss = total_loss / max(len(all_true), 1)
    acc = (all_preds == all_true).mean() if len(all_true) else 0.0
    return avg_loss, acc, all_true, all_preds


# --- Prints de verificación (rápidos) ---
print("DEVICE:", DEVICE)
print("INPUT_DIM:", INPUT_DIM, "| NUM_CLASSES:", NUM_CLASSES)
print("train_X:", train_X.shape, "train_y:", train_y.shape)
print("val_X  :", val_X.shape, "val_y  :", val_y.shape)

xb, yb = next(iter(train_dl))
with torch.no_grad():
    out = model(xb.to(DEVICE))
print("Sanity check batch -> xb:", xb.shape, "logits:", out.shape, "yb:", yb.shape)


best_val = -1.0
best_epoch = -1
best_path = "/content/mlp_best.pt"

for epoch in range(1, EPOCHS + 1):
    tr_loss, tr_acc, _, _ = run_epoch(train_dl, train=True)
    va_loss, va_acc, y_true, y_pred = run_epoch(val_dl, train=False)

    print(f"Epoch {epoch}/{EPOCHS} | train loss {tr_loss:.4f} acc {tr_acc:.3f} | val loss {va_loss:.4f} acc {va_acc:.3f}")

    if va_acc > best_val:
        best_val = va_acc
        best_epoch = epoch
        torch.save(model.state_dict(), best_path)

print("\n✅ Best val acc:", best_val, "| best epoch:", best_epoch, "| saved:", best_path)


# --- Evaluación final con el mejor checkpoint ---
# --- Evaluación final con el mejor checkpoint ---
model.load_state_dict(torch.load(best_path, map_location=DEVICE))
_, _, y_true, y_pred = run_epoch(val_dl, train=False)

labels_all = list(range(NUM_CLASSES))

print("\n📌 Classification report (VAL):")
print(classification_report(
    y_true, y_pred,
    labels=labels_all,
    target_names=LABELS,
    zero_division=0
))

cm = confusion_matrix(y_true, y_pred, labels=labels_all)
print("\n📌 Confusion matrix shape:", cm.shape)
print(cm)

# CELDA 17

# ✅ CELDA 17: Predicción interactiva y verificación de formato

def predict_proba(
    text,
    areas_top=None,
    dims_probs=None,
    tipo_fuente="mensaje",
    top_k=5,
    w_area=W_AREA,
    w_dims=W_DIMS,
):
    model.eval()
    with torch.no_grad():
        e = sbert.encode([text], convert_to_numpy=True, normalize_embeddings=True).astype(np.float32)[0]

        A = build_area_vec(areas_top) * float(w_area)
        D = build_dims_vec(dims_probs) * float(w_dims)
        T = build_tipo_vec(tipo_fuente)
        M = build_meta_vec(text)

        x = np.concatenate([e, A, D, T, M], axis=0).astype(np.float32)
        xb = torch.tensor(x, dtype=torch.float32).unsqueeze(0).to(DEVICE)

        logits = model(xb)[0]
        probs = torch.softmax(logits, dim=0).cpu().numpy()

        idx = np.argsort(probs)[::-1][:top_k]
        top = [(LABELS[i], float(probs[i])) for i in idx]
        return probs, top


# ✅ Tests mínimos
probs_test, _ = predict_proba("Movimiento parabólico: resolver problemas y calcular alcance")
assert probs_test.shape[0] == len(LABELS)
assert np.isclose(probs_test.sum(), 1.0, atol=1e-4)
assert np.all(probs_test >= 0) and np.all(probs_test <= 1)
print("✅ Unit tests OK (predict_proba)")



# ----------- MODO INTERACTIVO (texto libre) -----------
print("\n🧪 Modo prueba manual")
user_text = input("Ingresa un texto para clasificar:\n> ")

probs, top = predict_proba(
    user_text,
    areas_top=None,          # o ['FISICA']
    dims_probs=None,         # o {'hacer': 0.7, 'saber': 0.3}
    tipo_fuente="mensaje",
    top_k=5
)

print("\n🔎 Top predicciones:")
for lbl, p in top:
    print(f" - {lbl:25s}: {p:.3f}")

print("\n📊 Suma de probabilidades:", probs.sum())

# ✅ CELDA: Subir PDF -> chunking -> Red1(optional) -> Red2 -> recomendación

!pip -q install pypdf

import numpy as np
from pypdf import PdfReader
from google.colab import files

# ---------- helpers ----------
def read_pdf_text(path: str, max_pages: int = None) -> str:
    reader = PdfReader(path)
    pages = reader.pages[:max_pages] if max_pages else reader.pages
    texts = []
    for p in pages:
        t = p.extract_text() or ""
        t = t.replace("\x00", " ").strip()
        if t:
            texts.append(t)
    return "\n\n".join(texts)

def chunk_text(text: str, target_chars: int = 1200, overlap: int = 200):
    text = (text or "").strip()
    if not text:
        return []
    chunks = []
    i = 0
    n = len(text)
    while i < n:
        j = min(i + target_chars, n)

        # intenta cortar en un separador "bonito"
        cut = j
        for sep in ["\n\n", "\n", ". "]:
            k = text.rfind(sep, i, j)
            if k != -1 and k > i + target_chars * 0.5:
                cut = k + len(sep)
                break

        chunk = text[i:cut].strip()
        if len(chunk) > 40:
            chunks.append(chunk)

        i = max(cut - overlap, cut)  # overlap real
        if i == cut:  # evita loop infinito
            i += 1
    return chunks

def softmax_np(x):
    x = np.array(x, dtype=np.float32)
    x = x - x.max()
    ex = np.exp(x)
    return ex / (ex.sum() + 1e-9)

def topk_labels(probs, k=5):
    idx = np.argsort(probs)[::-1][:k]
    return [(LABELS[i], float(probs[i])) for i in idx]

# ---------- Red1 wrapper (opcional) ----------
def red1_features_for_text(text: str):
    """
    Si existe un objeto 'red1' (Red1Classifier) en memoria, usa sus features.
    Si no existe, devuelve None (neutro).
    """
    if "red1" in globals():
        out = red1.classify_text(text)
        return out.get("areas_top"), out.get("dims_probs")
    return None, None

# ---------- pipeline PDF -> recomendación ----------
def recommend_from_pdf(pdf_path: str, question: str = None, max_pages: int = None):
    full_text = read_pdf_text(pdf_path, max_pages=max_pages)
    chunks = chunk_text(full_text, target_chars=1200, overlap=200)

    if not chunks:
        raise ValueError("No pude extraer texto del PDF (puede ser escaneado).")

    # SBERT embeddings para similitud pregunta-chunk (si hay pregunta)
    if question and question.strip():
        q_emb = sbert.encode([question], convert_to_numpy=True, normalize_embeddings=True)[0]
        c_emb = sbert.encode(chunks, convert_to_numpy=True, normalize_embeddings=True)
        sims = (c_emb @ q_emb).astype(np.float32)  # cos sim por estar normalizados
        # pesos según similitud (softmax con temperatura)
        temp = 0.08  # más bajo = más "concentrado"
        weights = softmax_np(sims / temp)
        mode = "CON_PREGUNTA"
    else:
        sims = np.ones(len(chunks), dtype=np.float32)
        weights = np.ones(len(chunks), dtype=np.float32) / len(chunks)
        mode = "SIN_PREGUNTA_PROMEDIO"

    chunk_results = []
    probs_all = []

    for i, ch in enumerate(chunks):
        areas_top, dims_probs = red1_features_for_text(ch)
        probs, top = predict_proba(
            ch,
            areas_top=areas_top,
            dims_probs=dims_probs,
            tipo_fuente="archivo",   # porque viene de pdf
            top_k=5
        )
        probs_all.append(probs)
        chunk_results.append({
            "i": i,
            "w": float(weights[i]),
            "sim": float(sims[i]),
            "top": top,
            "preview": (ch[:240] + " ...") if len(ch) > 240 else ch
        })

    probs_all = np.vstack(probs_all)  # [n_chunks, n_labels]
    global_probs = (probs_all * weights.reshape(-1, 1)).sum(axis=0)
    global_probs = global_probs / (global_probs.sum() + 1e-9)

    # ordenar chunks por peso (si hay pregunta) o por prob de la etiqueta top global
    top_global = topk_labels(global_probs, k=5)
    best_label = top_global[0][0]
    best_label_idx = LABELS.index(best_label)

    # rank chunks por contribución a la etiqueta top
    contrib = probs_all[:, best_label_idx] * weights
    idx_rank = np.argsort(contrib)[::-1]

    print(f"\nMODE: {mode} | chunks: {len(chunks)}")
    if question and question.strip():
        print("PREGUNTA:", question)
    print("TOP global:", top_global)

    print("\n📌 Top chunks que soportan la recomendación principal:")
    for rank in range(min(5, len(chunks))):
        j = int(idx_rank[rank])
        print(f"\n  #{rank+1} chunk idx={j} weight={weights[j]:.3f} sim={sims[j]:.3f}")
        print("  top chunk:", chunk_results[j]["top"][:3])
        print("  preview:", chunk_results[j]["preview"])

    return global_probs, chunk_results

# ---------- UI: subir PDF ----------
uploaded = files.upload()
pdf_files = [k for k in uploaded.keys() if k.lower().endswith(".pdf")]
if not pdf_files:
    raise ValueError("Sube un archivo .pdf")

pdf_path = "/content/" + pdf_files[0]
print("✅ PDF cargado:", pdf_path)

# (opcional) pregunta para hacer recomendación contextual
question = input("Pregunta (ENTER = sin pregunta, recomendación global):\n> ").strip()

_ = recommend_from_pdf(pdf_path, question=question if question else None, max_pages=None)

# ✅ CELDA FINAL (única): subir PDF y recomendar (con POST automático)

!pip -q install pypdf
from google.colab import files
from pypdf import PdfReader
import numpy as np
import re

# -------------------------
# CONFIG
# -------------------------
CHUNK_WORDS = 220     # tamaño chunk (palabras)
CHUNK_OVERLAP = 40    # overlap (palabras)
TOP_CHUNKS_SHOW = 5   # cuantos chunks mostrar
TOPK_LABELS_PRINT = 5 # top labels a imprimir

# agregación por pregunta
TOPK_SPEC = 3
TOPK_GEN  = 12
SIM_TOP1_SPEC_TH = 0.62  # si top1 >= esto...
SIM_GAP_SPEC_TH  = 0.10  # ...y top1-top3 >= esto => ESPECÍFICA
TEMP_SPEC = 0.06
TEMP_GEN  = 0.16

# post
POST_ALPHA_DEFAULT = 0.85  # cuánto manda el post (0.6-1.0)

# -------------------------
# UTILIDADES
# -------------------------
EPS = 1e-9

def _softmax(x):
    x = x - np.max(x)
    ex = np.exp(x)
    return ex / (ex.sum() + EPS)

def topk_probs(probs, k=5):
    idx = np.argsort(probs)[::-1][:k]
    return [(LABELS[i], float(probs[i])) for i in idx]

def extract_pdf_text(pdf_path: str) -> str:
    reader = PdfReader(pdf_path)
    texts = []
    for i, page in enumerate(reader.pages):
        try:
            t = page.extract_text() or ""
        except Exception:
            t = ""
        t = re.sub(r"[ \t]+", " ", t)
        t = re.sub(r"\n{3,}", "\n\n", t).strip()
        if t:
            texts.append(t)
    return "\n\n".join(texts)

def chunk_text_words(text: str, chunk_words=220, overlap=40):
    words = re.findall(r"\S+", text)
    if not words:
        return []
    chunks = []
    step = max(chunk_words - overlap, 1)
    for start in range(0, len(words), step):
        end = min(start + chunk_words, len(words))
        chunk = " ".join(words[start:end]).strip()
        if len(chunk) >= 50:
            chunks.append(chunk)
        if end >= len(words):
            break
    return chunks

# -------------------------
# POST-PROCESADO POR INTENCIÓN (query-aware)
# -------------------------
INTENT_BOOSTS = [
    (r"\b(cuestionario|quiz|prueba|evaluaci[oó]n|opci[oó]n m[uú]ltiple|test)\b",
     {"EVALUACION_CUESTIONARIO": 2.2, "ACTIVIDAD_PRACTICA": 0.4}),
    (r"\b(video|youtube|audiovisual|documental|ver un video)\b",
     {"VIDEO": 2.1}),
    (r"\b(mapa conceptual|mapa mental|esquema|organizador gr[aá]fico)\b",
     {"MAPA_CONCEPTUAL": 2.2, "PRESENTACION": 0.7}),
    (r"\b(presentaci[oó]n|diapositivas|ppt|exponer)\b",
     {"PRESENTACION": 2.0}),
    (r"\b(debate|discute|argumenta|opina|postura|mesa redonda|foro)\b",
     {"DEBATE_SOCRATICO": 2.1}),
    (r"\b(dramatiza|dramatizaci[oó]n|roleplay|representen|act[uú]en|escenifica)\b",
     {"DRAMATIZACION_ROLEPLAY": 2.2}),
    (r"\b(simula|simulaci[oó]n|phet|interactivo|manipular variables)\b",
     {"SIMULACION_INTERACTIVA": 2.1}),
    (r"\b(proyecto|prototipo|maker|construye|feria|producto)\b",
     {"PROYECTO_MAKER": 1.9, "ACTIVIDAD_PRACTICA": 0.6}),
    (r"\b(gamific|misiones|retos|puntos|insignias|ranking|escape room)\b",
     {"JUEGO_GAMIFICADO": 2.2, "ACTIVIDAD_PRACTICA": 0.7}),
    (r"\b(did[aá]ctic|c[oó]mo explicar|c[oó]mo ense[nñ]ar|estrategia|din[aá]mica)\b",
     {"ACTIVIDAD_PRACTICA": 0.9, "PRESENTACION": 0.9}),
]

def postprocess_probs(probs_model, query_text=None, alpha=POST_ALPHA_DEFAULT):
    p = np.asarray(probs_model, dtype=np.float32)
    p = p / (p.sum() + EPS)

    boost = np.zeros_like(p, dtype=np.float32)

    if query_text:
        q = query_text.lower().strip()
        for pat, adds in INTENT_BOOSTS:
            if re.search(pat, q):
                for lbl, w in adds.items():
                    if lbl in label2id:
                        boost[label2id[lbl]] += float(w)

    logits = np.log(p + EPS) + float(alpha) * boost
    p2 = _softmax(logits).astype(np.float32)
    return p2

# -------------------------
# AGREGADOR POR CHUNKS
# -------------------------
def embed_one(text: str):
    # usa tu SBERT ya cargado
    e = sbert.encode([text], convert_to_numpy=True, normalize_embeddings=True).astype(np.float32)[0]
    return e

def cosine(a, b):
    # a,b normalizados -> dot
    return float(np.dot(a, b))

def aggregate_for_pdf(chunks, question=None):
    # 1) probas por chunk (Red2)
    chunk_probs = []
    for ch in chunks:
        p, _ = predict_proba(ch, tipo_fuente="archivo", top_k=TOPK_LABELS_PRINT)
        chunk_probs.append(p)
    chunk_probs = np.vstack(chunk_probs)  # [N, C]

    # 2) sin pregunta => promedio simple
    if not question or not question.strip():
        w = np.ones(len(chunks), dtype=np.float32)
        w = w / (w.sum() + EPS)
        probs_global = (chunk_probs * w[:, None]).sum(axis=0)
        mode = "SIN_PREGUNTA_PROMEDIO"
        sims = np.ones(len(chunks), dtype=np.float32)
        idx_sorted = np.argsort(-w)
        return probs_global, w, sims, idx_sorted, mode

    # 3) con pregunta => pesos por similitud (query vs chunk)
    q = question.strip()
    qE = embed_one(q)
    cE = np.vstack([embed_one(ch) for ch in chunks])

    sims = np.array([cosine(qE, cE[i]) for i in range(len(chunks))], dtype=np.float32)
    idx = np.argsort(-sims)

    top1 = float(sims[idx[0]])
    top3 = float(sims[idx[min(2, len(idx)-1)]]) if len(idx) >= 3 else float(sims[idx[0]])
    gap = top1 - top3

    is_spec = (top1 >= SIM_TOP1_SPEC_TH) and (gap >= SIM_GAP_SPEC_TH)
    k = min(TOPK_SPEC if is_spec else TOPK_GEN, len(chunks))
    temp = TEMP_SPEC if is_spec else TEMP_GEN

    top_idx = idx[:k]
    top_sims = sims[top_idx]
    weights = _softmax(top_sims / max(temp, 1e-6)).astype(np.float32)

    probs_global = (chunk_probs[top_idx] * weights[:, None]).sum(axis=0)
    mode = "CON_PREGUNTA_ESPECIFICA" if is_spec else "CON_PREGUNTA_GENERAL"
    return probs_global, weights, top_sims, top_idx, mode

# -------------------------
# RUN: SUBIR PDF + PREGUNTA + SALIDA YA POST-PROCESADA
# -------------------------
up = files.upload()
pdf_name = list(up.keys())[0]
pdf_path = f"/content/{pdf_name}"
print("✅ PDF cargado:", pdf_path)

full_text = extract_pdf_text(pdf_path)
chunks = chunk_text_words(full_text, CHUNK_WORDS, CHUNK_OVERLAP)
if not chunks:
    raise RuntimeError("No pude extraer texto del PDF (o quedó vacío). Prueba otro PDF.")

print(f"📄 {pdf_name} | chunks: {len(chunks)}")
question = input("Pregunta (ENTER = sin pregunta, recomendación global):\n> ")

# 1) Agregar probs (modelo)
probs_global, weights, sims_used, idx_used, mode = aggregate_for_pdf(chunks, question=question)

# 2) POST: SIEMPRE, pero si no hay pregunta será casi neutro (sin boosts)
probs_final = postprocess_probs(probs_global, query_text=(question.strip() if question else None), alpha=POST_ALPHA_DEFAULT)

print("\nMODE:", mode, "| chunks usados:", len(idx_used) if (question and question.strip()) else len(chunks))
if question and question.strip():
    print("PREGUNTA:", question.strip())

print("TOP global (YA POST):", topk_probs(probs_final, TOPK_LABELS_PRINT))

print("\n📌 Top chunks que soportan la recomendación principal:")
# si no hay pregunta -> mostramos top chunks por "peso uniforme" (todos iguales), igual mostramos primeros
if not (question and question.strip()):
    show_idx = list(range(min(TOP_CHUNKS_SHOW, len(chunks))))
    for rank, ci in enumerate(show_idx, 1):
        p_ch, _ = predict_proba(chunks[ci], tipo_fuente="archivo", top_k=3)
        p_ch2 = postprocess_probs(p_ch, query_text=None, alpha=POST_ALPHA_DEFAULT)
        prev = (chunks[ci][:260] + " ...") if len(chunks[ci]) > 260 else chunks[ci]
        print(f"\n  #{rank} chunk idx={ci} weight=1.000")
        print("  top chunk (post):", topk_probs(p_ch2, 3))
        print("  preview:", prev.replace("\n"," ") )
else:
    # con pregunta: idx_used ya es top-k, weights alineado a idx_used
    for rank in range(min(TOP_CHUNKS_SHOW, len(idx_used))):
        ci = int(idx_used[rank])
        w = float(weights[rank])
        sim = float(sims_used[rank])
        p_ch, _ = predict_proba(chunks[ci], tipo_fuente="archivo", top_k=3)
        p_ch2 = postprocess_probs(p_ch, query_text=question.strip(), alpha=POST_ALPHA_DEFAULT)
        prev = (chunks[ci][:260] + " ...") if len(chunks[ci]) > 260 else chunks[ci]
        print(f"\n  #{rank+1} chunk idx={ci} weight={w:.3f} sim={sim:.3f}")
        print("  top chunk (post):", topk_probs(p_ch2, 3))
        print("  preview:", prev.replace("\n"," ") )

# CELDA 18

# Demo: salida lista para guiar al LLM Explicación: aquí generas el “paquete” que tu backend le mandará al LLM.

import os, json, torch

EXPORT_DIR = "/content/export_red2_final"
os.makedirs(EXPORT_DIR, exist_ok=True)

# 1) pesos MLP
torch.save(model.state_dict(), os.path.join(EXPORT_DIR, "mlp_state.pt"))

# 2) config principal
config = {
    "sbert_name": SBERT_NAME,
    "labels": LABELS,
    "area_order": AREA_ORDER,
    "dim_order": DIM_ORDER,
    "emb_dim": EMB_DIM,
    "input_dim": int(INPUT_DIM),

    # pesos de features (si los usas en inferencia)
    "w_area": float(W_AREA) if "W_AREA" in globals() else 1.0,
    "w_dims": float(W_DIMS) if "W_DIMS" in globals() else 1.0,

    # chunking + selección por pregunta
    "chunk_words": int(CHUNK_WORDS) if "CHUNK_WORDS" in globals() else 220,
    "chunk_overlap": int(CHUNK_OVERLAP) if "CHUNK_OVERLAP" in globals() else 40,
    "top_chunks_show": int(TOP_CHUNKS_SHOW) if "TOP_CHUNKS_SHOW" in globals() else 5,

    "topk_spec": int(TOPK_SPEC) if "TOPK_SPEC" in globals() else 3,
    "topk_gen": int(TOPK_GEN) if "TOPK_GEN" in globals() else 12,
    "sim_top1_spec_th": float(SIM_TOP1_SPEC_TH) if "SIM_TOP1_SPEC_TH" in globals() else 0.62,
    "sim_gap_spec_th": float(SIM_GAP_SPEC_TH) if "SIM_GAP_SPEC_TH" in globals() else 0.10,
    "temp_spec": float(TEMP_SPEC) if "TEMP_SPEC" in globals() else 0.06,
    "temp_gen": float(TEMP_GEN) if "TEMP_GEN" in globals() else 0.16,

    # post
    "post_alpha": float(POST_ALPHA_DEFAULT) if "POST_ALPHA_DEFAULT" in globals() else 0.85,
}

with open(os.path.join(EXPORT_DIR, "config.json"), "w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

# 3) reglas del post (boosts)
# si tu celda final definió INTENT_BOOSTS, lo exportamos
intent_boosts = []
if "INTENT_BOOSTS" in globals():
    for pat, adds in INTENT_BOOSTS:
        intent_boosts.append({"pattern": pat, "adds": adds})

with open(os.path.join(EXPORT_DIR, "intent_boosts.json"), "w", encoding="utf-8") as f:
    json.dump(intent_boosts, f, ensure_ascii=False, indent=2)

print("✅ Export listo en:", EXPORT_DIR)
print("Archivos:", os.listdir(EXPORT_DIR))

import shutil, os
zip_path = "/content/export_red2_final.zip"
shutil.make_archive("/content/export_red2_final", "zip", "/content/export_red2_final")
print("✅ ZIP:", zip_path)